### ISSUE TITLE
Livestreaming fra hjemmeside

### ISSUE THREAD

**Issue by ThomasTuxTech** [peterbrinck/rolfbjerre#3]
Hej Peter
Rolf ide er at han vil livestreame sin sidste uge af valgkampen med mulighed for et kommentarspor eller -forum. Det er det jeg foreløbig ved om projektet :)
Thomas

**Comment by ThomasTuxTech** [comment]
Rolf har netop bildt mig ind at du kender alt til den der video et eller andet konto til livestream :) Planen er at han gerne ville gå online fra i morgen aften (onsdag). Bip mig hvis spørgsmål (93 10 81 87).

**Comment by ThomasTuxTech** [comment]
Det kører smukt. Lidt pix men til at leve med. Lyden er super god. Når du opretter menupunktet "Share with care", så skal vi vel også have et til live streaming. Måske kunne vi kalde det LivePolitik :)

**Comment by nsturis** [comment]
Det er skide fedt, det fungerer upåklageligt! Lige en lille (småirriterende) rettelse, så er det 'laboratorier' i stedet for 'labratorier' :)

**Comment by peterbrinck** [comment]
@ThomasTuxTech 
Det kommer

@Diatz 
Det bliver rettet! :smile:
