### ISSUE TITLE
Stof til hjemmesiden undersider

### ISSUE THREAD

**Issue by ThomasTuxTech** [peterbrinck/rolfbjerre#4]
Hej Peter

Sisse Haynes her smidt nogle løse ender videre til mig. Hun er ikke GitHub girl, så jeg smider den ind og står for kontakten hvis du har spørgsmål. Hun har vist pinget dig tidligere om det på Facebook :)
1. På forsiden er der noget dummy tekst (Hi + Social) som kunne fjernes, fordi de 7 billeder med tekst i toppen giver de informationer (tidleigere issue).
2. "Lala" teksten i toppen af Mærkesager må du godt fjerne. Mærkesagerne står jo smukt i bunden (0 - 3).
3. "Om Rolf" giver Path not found. Kunne vi måske bruge de to billede (de 7 med tekst) om Rolf som menneske og politiker. I hvert fald bedre end ingenting.
4. "Kontakt" giver Path not found. Der har Sisse leveret tekst til.

Thomas

Copy&Paste af info fra Sisse om stof til hjemmesiden:

KONTAKT

Du er velkommen til at kontakte Rolf Bjerre på: rolf.bjerre@alternativet.dk eller på tlf.: 2769 3126
Har du lyst til at bidrage til Rolf’s kampagne eller joine Team Rolf, kontakt da Nicolai Møller på: nicolai_moeller@hotmail.com eller tlf.: 2257 4902
For presse-relateret kontakt, se PRESSE (link videre)

PRESSE

PR - & pressechef: 
Sisse Haynes
E-mail: sisse.haynes@alternativet.dk
Tlf: 2629 0550 

PRESSEBILLEDER

Officielt kandidatbilleder: 
http://wiki.alternativet.dk/images/thumb/5/50/Portr%C3%A6t_rolf-bjerre_BW1.jpg/800px-Portr%C3%A6t_rolf-bjerre_BW1.jpg
http://wiki.alternativet.dk/images/6/61/Portr%C3%A6t_rolf-bjerre1.jpg
https://drive.google.com/file/d/0B5OJX7M7OGiCRlhIZDBLa3FpRzQ/view?usp=sharing
https://drive.google.com/open?id=0B5OJX7M7OGiCMzVYdHhDQUJRc0E&authuser=0 

Andre billeder: 

https://drive.google.com/open?id=0B5OJX7M7OGiCdlhUZDZwQ291cmc&authuser=0
https://drive.google.com/open?id=0B5OJX7M7OGiCLWtpY2ctU3NYaFk&authuser=0
https://drive.google.com/open?id=0B5OJX7M7OGiCRWVpMHRmOHl4cEU&authuser=0
https://scontent-ams.xx.fbcdn.net/hphotos-xpf1/t31.0-8/11067496_10153758317567892_5619317291945182192_o.jpg
https://drive.google.com/open?id=0B5OJX7M7OGiCdkxmWDBRaE9ieUU&authuser=0
https://drive.google.com/open?id=0B5OJX7M7OGiCYXpWZi1DWWQwbVE&authuser=0

Officielle logoer:

http://wiki.alternativet.dk/images/thumb/f/f4/Alt_Logo_Horizontal_S_Vector_RGB-01.png/1600px-Alt_Logo_Horizontal_S_Vector_RGB-01.png
http://wiki.alternativet.dk/images/2/29/Alt_Logo_L_1000x825_72dpi_RGB.png
http://wiki.alternativet.dk/images/0/0d/Logo_%C3%85_sortcirkel.png
http://wiki.alternativet.dk/images/e/e8/Logo_heltgr%C3%B8n_rgb2.png

**Comment by peterbrinck** [comment]
Alt indhold som IKKE er fra jer af, er udelukkende placeholder, så det bliver fjernet med tiden

Og, alt er ved at falde på plads nu

**Comment by ThomasTuxTech** [comment]
Bare lige for at være sikker på jeg forstår det korrekt. Med Placeholder menes at det ligger som en ressource et andet sted end på hjemmesiden?

**Comment by peterbrinck** [comment]
Nej, en placeholder er udelukkende for at vise at her, skal der være noget
I denne situation, er det tekst.

**Comment by ThomasTuxTech** [comment]
Ah, de der dummy tekster, som tegn på at "her mangler tekst". Tak for det.

**Comment by ThomasTuxTech** [comment]
Der er for mig at se to ting tilbage, som hvis de bliver fikset, vil få siden til at se færdig ud: 
1. Du må meget gerne fjerne den der "Title Goes Here" under "Om Rolf". Hvis han senere kommer med mere tekst til den side, så tager vi den derfra.
2. Kontakt side vil det være super at få op og køre. Hvis du mangler noget til den, så giv endelig lyd.

"Share with care" + guides må komme sidst i køen. Livestreamingen skal jeg se at få skaffet noget info om, så du får noget konkret at arbejde med.

**Comment by peterbrinck** [comment]
Livestream har jeg helt på plads, jeg har sat server og det hele op, og vi har testet det

Men umiddelbart, så mangler jeg ikke noget info fra jer af, det er bare mig som skal give den en skalle :wink: 
I morgen aften tror jeg at siden er 100% færdig, og så kan vi finpudse og tilføje div. ekstra ting som ikke er essentielle

**Comment by ThomasTuxTech** [comment]
Super. Du har lige svaret på det jeg skrev under Livestream. Det er bare konge!!!

**Comment by peterbrinck** [comment]
Closed by commit ab0a830
