### ISSUE TITLE
Håndtering af flere live streaminger på valgdagen

### ISSUE THREAD

**Issue by ThomasTuxTech** [peterbrinck/rolfbjerre#9]
På valgdagen får vi flere live kamera op og kører. Så vidt jeg har forstå kan hangout håndterer op til 10 kamera. Derfor vil det være super hvis vi kan lave en eller anden form for skærm, hvor folk kan vælge mellem de forskellige live streaminger.

Kan man lave en eller anden form for "skema", fx 3 x 3 = 9 streams (små skærme), hvor de aktive streams vises og den besøge kan vælge en af dem (som så bliver til en stor skærm).

Jeg håber det giver mening. Ellers bip mig.

**Comment by peterbrinck** [comment]
Jeg får kigget på det

**Comment by ThomasTuxTech** [comment]
Jeg forstod på Rolf at det virkede lidt on og off med flere kamera. Og at der kom en eller anden service ind over, 23 et eller andet. Sådan er det jo når musikken spiller. Lad os endelig beholde muligheden for at have flere livestreams kørende. Jeg er gået i tænkeboks for at finde nogle gode navne til de 3 kameraer.
